### ISSUE TITLE
[bug] {ping} always show -9

### ISSUE THREAD

**Issue by hkkongou** [HSGamer/BetterBoard#78]
Given
```
type: animated
title:
  list:
    - "&ca server"
    - "&da server"
  async: true
  update: 20
lines:
      - ""
      - "&eplayer name: &b{player} "
      - list:
        - "&eping: &b{ping}ms"
        async: false
        update: 5
```
The {ping} always show -9
BetterBoard-2.3 
folia-bundler-1.20.1-R0.1-SNAPSHOT-reobf

![image](https://github.com/HSGamer/BetterBoard/assets/61608872/f9ef5d3e-a054-4d66-aaed-9156dbc83e55)
